-- RunAI Supabase schema
-- Target database: Supabase PostgreSQL
-- Auth model: Supabase Auth owns accounts in auth.users.
-- Application profile data lives in public.profiles.
-- Do not store password_hash in public tables.

create extension if not exists pgcrypto;

do $$
begin
  create type goal_status as enum ('active', 'completed', 'cancelled');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type run_source as enum ('manual', 'quest');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type training_plan_status as enum ('active', 'completed', 'cancelled');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type quest_status as enum ('locked', 'available', 'completed', 'failed', 'expired');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type progress_status as enum ('completed', 'failed', 'expired');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type ai_trigger_type as enum ('initial_plan', 'failed_quest', 'expired_quest');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type adjustment_status as enum ('pending', 'accepted', 'rejected');
exception
  when duplicate_object then null;
end $$;

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email varchar(255) not null unique,
  name varchar(120),
  age integer check (age is null or age > 0),
  weight numeric(5,2) check (weight is null or weight > 0),
  height numeric(5,2) check (height is null or height > 0),
  experience_level varchar(50) not null default 'beginner',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists goals (
  goal_id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(user_id) on delete cascade,
  goal_type varchar(120) not null,
  target_distance numeric(6,2) not null check (target_distance > 0),
  target_duration_minutes integer check (target_duration_minutes is null or target_duration_minutes > 0),
  target_date date not null,
  status goal_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists runs (
  run_id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(user_id) on delete cascade,
  run_date date not null,
  distance numeric(6,2) not null check (distance > 0),
  duration_minutes integer not null check (duration_minutes > 0),
  run_type varchar(80) not null,
  source run_source not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists training_plans (
  training_plan_id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(user_id) on delete cascade,
  goal_id bigint not null references goals(goal_id) on delete cascade,
  start_date date not null,
  end_date date not null,
  status training_plan_status not null default 'active',
  version integer not null default 1,
  source varchar(80) not null default 'ai',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists training_sessions (
  training_session_id bigint generated by default as identity primary key,
  training_plan_id bigint not null references training_plans(training_plan_id) on delete cascade,
  session_date date not null,
  training_type varchar(80) not null,
  target_distance numeric(6,2) not null check (target_distance > 0),
  target_duration_minutes integer check (target_duration_minutes is null or target_duration_minutes > 0),
  status quest_status not null default 'locked',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_training_sessions_plan_date unique (training_plan_id, session_date)
);

create table if not exists training_progress (
  training_progress_id bigint generated by default as identity primary key,
  training_session_id bigint not null unique references training_sessions(training_session_id) on delete cascade,
  run_id bigint references runs(run_id) on delete set null,
  status progress_status not null,
  actual_distance numeric(6,2),
  actual_duration_minutes integer,
  failure_reason text,
  strava_image_url text,
  submitted_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists ai_analysis (
  ai_analysis_id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(user_id) on delete cascade,
  training_plan_id bigint not null references training_plans(training_plan_id) on delete cascade,
  trigger_type ai_trigger_type not null,
  result_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists plan_adjustments (
  plan_adjustment_id bigint generated by default as identity primary key,
  training_plan_id bigint not null references training_plans(training_plan_id) on delete cascade,
  ai_analysis_id bigint not null references ai_analysis(ai_analysis_id) on delete cascade,
  reason text,
  status adjustment_status not null default 'pending',
  proposed_sessions jsonb not null,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_training_plans_one_active_per_user
  on training_plans (user_id)
  where status = 'active';

create index if not exists idx_goals_user_status on goals (user_id, status);
create index if not exists idx_runs_user_date on runs (user_id, run_date desc);
create index if not exists idx_training_sessions_plan_date on training_sessions (training_plan_id, session_date);
create index if not exists idx_ai_analysis_user_plan on ai_analysis (user_id, training_plan_id);

drop trigger if exists set_profiles_updated_at on profiles;
create trigger set_profiles_updated_at
  before update on profiles
  for each row execute function set_updated_at();

drop trigger if exists set_goals_updated_at on goals;
create trigger set_goals_updated_at
  before update on goals
  for each row execute function set_updated_at();

drop trigger if exists set_runs_updated_at on runs;
create trigger set_runs_updated_at
  before update on runs
  for each row execute function set_updated_at();

drop trigger if exists set_training_plans_updated_at on training_plans;
create trigger set_training_plans_updated_at
  before update on training_plans
  for each row execute function set_updated_at();

drop trigger if exists set_training_sessions_updated_at on training_sessions;
create trigger set_training_sessions_updated_at
  before update on training_sessions
  for each row execute function set_updated_at();

drop trigger if exists set_training_progress_updated_at on training_progress;
create trigger set_training_progress_updated_at
  before update on training_progress
  for each row execute function set_updated_at();

drop trigger if exists set_ai_analysis_updated_at on ai_analysis;
create trigger set_ai_analysis_updated_at
  before update on ai_analysis
  for each row execute function set_updated_at();

drop trigger if exists set_plan_adjustments_updated_at on plan_adjustments;
create trigger set_plan_adjustments_updated_at
  before update on plan_adjustments
  for each row execute function set_updated_at();

alter table profiles enable row level security;
alter table goals enable row level security;
alter table runs enable row level security;
alter table training_plans enable row level security;
alter table training_sessions enable row level security;
alter table training_progress enable row level security;
alter table ai_analysis enable row level security;
alter table plan_adjustments enable row level security;

drop policy if exists profiles_select_own on profiles;
create policy profiles_select_own on profiles
  for select using (auth.uid() = user_id);

drop policy if exists profiles_update_own on profiles;
create policy profiles_update_own on profiles
  for update using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists goals_own on goals;
create policy goals_own on goals
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists runs_own on runs;
create policy runs_own on runs
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists training_plans_own on training_plans;
create policy training_plans_own on training_plans
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists training_sessions_own on training_sessions;
create policy training_sessions_own on training_sessions
  for all using (
    exists (
      select 1
      from training_plans
      where training_plans.training_plan_id = training_sessions.training_plan_id
        and training_plans.user_id = auth.uid()
    )
  );

drop policy if exists training_progress_own on training_progress;
create policy training_progress_own on training_progress
  for all using (
    exists (
      select 1
      from training_sessions
      join training_plans on training_plans.training_plan_id = training_sessions.training_plan_id
      where training_sessions.training_session_id = training_progress.training_session_id
        and training_plans.user_id = auth.uid()
    )
  );

drop policy if exists ai_analysis_own on ai_analysis;
create policy ai_analysis_own on ai_analysis
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists plan_adjustments_own on plan_adjustments;
create policy plan_adjustments_own on plan_adjustments
  for all using (
    exists (
      select 1
      from training_plans
      where training_plans.training_plan_id = plan_adjustments.training_plan_id
        and training_plans.user_id = auth.uid()
    )
  );
